version: "3.8"

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./server:/app

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: client.dockerfile
    env_file:
      - ./client/.env.local
    ports:
      - "3000:3000"
