import "./globals.css";
import "react-tooltip/dist/react-tooltip.css";
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LeftSidebar from "./components/LeftSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head></head>
      <body
        className={`${inter.className} bg-main-bg text-text-primary h-screen w-screen`}
      >
        <div className="flex h-full w-full">
          <main className="flex-1 h-full w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
