"""empty message

Revision ID: 4c932635cfea
Revises: 
Create Date: 2023-11-09 18:52:28.158271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c932635cfea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant', sa.Column('accuracy', sa.Float(), nullable=True))
    op.drop_column('applicant', 'model_accuracy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant', sa.Column('model_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('applicant', 'accuracy')
    # ### end Alembic commands ###
